# Generated by Django 3.2.3 on 2021-06-29 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('producto', '0004_alter_producto_imagen'),
        ('cuentas', '0002_remove_perfil_fecha_nacimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveBigIntegerField()),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='producto.producto')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cuentas.perfil')),
            ],
        ),
    ]
