# Generated by Django 3.2.3 on 2021-06-29 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0002_remove_perfil_fecha_nacimiento'),
        ('carrito', '0002_alter_carrito_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuentas.perfil'),
        ),
    ]
