<<<<<<< HEAD
# Generated by Django 3.2.3 on 2021-07-02 00:12
=======
# Generated by Django 3.2.3 on 2021-07-01 22:41
>>>>>>> 9331225dc2d0da78585d19164eacc8040d6377e6

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0003_alter_carrito_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='cantidad',
            field=models.PositiveBigIntegerField(blank=True, default=1, null=True),
        ),
    ]
