# Generated by Django 3.2.3 on 2021-07-02 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0003_alter_carrito_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='cantidad',
            field=models.PositiveBigIntegerField(blank=True, default=1, null=True),
        ),
    ]
