# Generated by Django 3.2.3 on 2021-07-02 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0004_alter_producto_imagen'),
        ('carrito', '0004_alter_carrito_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='producto.producto'),
        ),
    ]
