# Generated by Django 3.2.3 on 2021-06-13 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre:')),
                ('descripcion', models.TextField(max_length=150, verbose_name='Descripción')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre Producto:')),
                ('precio', models.PositiveIntegerField(verbose_name='Precio:')),
                ('stock', models.IntegerField(verbose_name='Stock:')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creacion:')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Actualizado:')),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='producto.categoria')),
            ],
        ),
    ]
