# Generated by Django 3.2.3 on 2021-06-20 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0002_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='descuento',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='descuento:'),
        ),
        migrations.AddField(
            model_name='producto',
            name='estadooferta',
            field=models.BooleanField(default=0, verbose_name='estadooferta:'),
        ),
    ]
