# Generated by Django 3.2.3 on 2021-06-25 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0003_auto_20210620_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(upload_to='productos', verbose_name='Imagen:'),
        ),
    ]
