# Generated by Django 3.2.3 on 2021-07-02 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='imagen',
            field=models.ImageField(default='', upload_to='perfil', verbose_name='Imagen perfil:'),
        ),
    ]
