# Generated by Django 3.2.3 on 2021-07-02 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0002_perfil_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='admin',
            field=models.BooleanField(default=0, verbose_name='Admin'),
        ),
    ]
