# Generated by Django 3.2.3 on 2021-06-30 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0002_remove_perfil_fecha_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
