<<<<<<< HEAD
# Generated by Django 3.2.3 on 2021-07-02 00:18
=======
# Generated by Django 3.2.3 on 2021-07-01 22:42
>>>>>>> 9331225dc2d0da78585d19164eacc8040d6377e6

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0003_alter_perfil_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
