# Generated by Django 3.2.3 on 2021-07-02 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0007_perfil_imagen'),
        ('cuentas', '0007_remove_perfil_imagen'),
    ]

    operations = [
    ]
