# Generated by Django 3.2.3 on 2021-07-02 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(max_length=499, verbose_name='Caja de Comentarios')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Subida')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuentas.perfil')),
            ],
        ),
    ]
