# Generated by Django 3.2.3 on 2021-07-02 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0002_auto_20210702_0247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='descripcion',
            field=models.TextField(max_length=399, verbose_name='Caja de Comentarios'),
        ),
    ]
