# Generated by Django 3.2.3 on 2021-07-02 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0003_alter_comentario_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='descripcion',
            field=models.TextField(max_length=499, verbose_name='Caja de Comentarios'),
        ),
    ]
